---
- name: ðŸŽ¯ ImplementaciÃ³n completa Ansible Nivel 4 - Laboratorio AcadÃ©mico
  hosts: lab_academico
  become: yes
  gather_facts: yes
  
  roles:
    - almacenamiento_sistemas
    - procesos_servicios
    - red_lab  
    - tareas_automatizadas
    - usuarios_permisos
